package day8

import kotlin.test.Test
import kotlin.test.assertEquals

class Test {
    private val input = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().lines()

    @Test
    fun part1Example() {
        val calibrations = Antinodes.parse(input)
        val singleLocationsCount = calibrations.singleLocationsCount()
         assertEquals(14, singleLocationsCount)
    }

    @Test
    fun part2Example() {
        val calibrations = Antinodes.parse(input)
        val lineLocationsCount = calibrations.lineLocationsCount()
         assertEquals(34, lineLocationsCount)
    }
}